import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { Sidebar } from "@/components/sidebar";
import { playlists } from "@/data/playlists";
import { Menu } from "@/components/menu";
import { ScrollArea } from "@/components/ui/scroll-area";
import { SWRConfig } from "swr";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased overflow-y-hidden",
					fontSans.variable,
				)}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<div>
						<Menu />
						<div className="border-t">
							<div className="bg-background">
								<div className="grid lg:grid-cols-5">
									<Sidebar className="hidden lg:block" />
									<div className="col-span-3 lg:col-span-4 lg:border-l">
											{children}
										
									</div>
								</div>
							</div>
						</div>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
